/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converterApp;

import java.awt.event.ItemEvent;
import java.text.NumberFormat;

/**
 *
 * @author Azhar, Alex, Jeydan, Russel
 */
public class ConverterView extends javax.swing.JPanel {
    private String[] ISUnits = {"cm","metre","km","C"};
    private String[] USUnits = {"inch","feet","yard","F"};
    private NumberFormat numFormat;
    /**
     * Creates new form ConverterView
     */
    public ConverterView() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lbl_unit1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        lb_unit2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cbox_sourceUnit = new javax.swing.JComboBox(ISUnits);
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        cbox_targetUnit = new javax.swing.JComboBox(USUnits);
        toggleBtn_switch = new javax.swing.JToggleButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel1.setText("Converter Application");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jTextField1, gridBagConstraints);

        lbl_unit1.setText(cbox_sourceUnit.getSelectedItem().toString());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lbl_unit1, gridBagConstraints);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jTextField2, gridBagConstraints);

        lb_unit2.setText(cbox_targetUnit.getSelectedItem().toString());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lb_unit2, gridBagConstraints);

        jButton1.setText("Convert");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jButton1, gridBagConstraints);

        cbox_sourceUnit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbox_sourceUnitItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(cbox_sourceUnit, gridBagConstraints);

        jLabel4.setText("Numbers after Decimal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jTextField3, gridBagConstraints);

        cbox_targetUnit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbox_targetUnitItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(cbox_targetUnit, gridBagConstraints);

        toggleBtn_switch.setText("Switch");
        toggleBtn_switch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                toggleBtn_switchItemStateChanged(evt);
            }
        });
        toggleBtn_switch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleBtn_switchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(toggleBtn_switch, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void toggleBtn_switchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_toggleBtn_switchItemStateChanged
        // TODO add your handling code here:
        int selectedSourceIndex = cbox_sourceUnit.getSelectedIndex();
        int selectedTargetIndex = cbox_targetUnit.getSelectedIndex();
        if(evt.getStateChange() == ItemEvent.DESELECTED){
            cbox_sourceUnit.setModel(new javax.swing.DefaultComboBoxModel(ISUnits));
            cbox_targetUnit.setModel(new javax.swing.DefaultComboBoxModel(USUnits));          
        } else {
            cbox_sourceUnit.setModel(new javax.swing.DefaultComboBoxModel(USUnits));
            cbox_targetUnit.setModel(new javax.swing.DefaultComboBoxModel(ISUnits));
        }
        cbox_sourceUnit.setSelectedIndex(selectedTargetIndex);
        cbox_targetUnit.setSelectedIndex(selectedSourceIndex);
        lbl_unit1.setText(cbox_sourceUnit.getSelectedItem().toString());
        lb_unit2.setText(cbox_targetUnit.getSelectedItem().toString());
    }//GEN-LAST:event_toggleBtn_switchItemStateChanged

    private void cbox_sourceUnitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbox_sourceUnitItemStateChanged
        // TODO add your handling code here:
        lbl_unit1.setText(cbox_sourceUnit.getSelectedItem().toString());
       
    }//GEN-LAST:event_cbox_sourceUnitItemStateChanged

    private void cbox_targetUnitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbox_targetUnitItemStateChanged
        // TODO add your handling code here:
         lb_unit2.setText(cbox_targetUnit.getSelectedItem().toString());
    }//GEN-LAST:event_cbox_targetUnitItemStateChanged

    private void toggleBtn_switchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleBtn_switchActionPerformed
        
    }//GEN-LAST:event_toggleBtn_switchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbox_sourceUnit;
    private javax.swing.JComboBox cbox_targetUnit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lb_unit2;
    private javax.swing.JLabel lbl_unit1;
    private javax.swing.JToggleButton toggleBtn_switch;
    // End of variables declaration//GEN-END:variables
}
